import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true });
const base = process.env.PREVIEW_URL || 'http://127.0.0.1:4183';
await mkdir('qa', { recursive: true });
const errors = [];
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.on('pageerror', error => errors.push(error.message));
await page.clock.install();
await page.goto(base);
await page.locator('.fox-pet').waitFor();
await page.evaluate(() => { const image = new Image(); image.src = '/assets/chat/fox-pixel-approved.png'; return image.decode(); });
const before = await page.locator('.fox-pet').boundingBox();
await page.evaluate(() => window.scrollTo(0, 900));
assert.deepEqual(await page.locator('.fox-pet').boundingBox(), before);
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({ path: 'qa/fox-desktop-closed.png' });
await page.clock.fastForward(120_000);
assert.equal(await page.locator('.fox-pet').getAttribute('data-pose'), 'seated');
assert.deepEqual(await page.locator('.fox-pet').boundingBox(), before);
assert.equal(await page.locator('.fox-pet animateTransform').count(), 1);
assert.equal(await page.locator('.fox-body animateTransform').count(), 0);
await page.locator('.fox-pet').click();
assert.equal(await page.locator('.fox-panel').isVisible(), true);
await page.screenshot({ path: 'qa/fox-desktop-open.png' });
await page.route('**/api/chat', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'My AI connection is still being set up.' }) }));
await page.locator('textarea').fill('What is Lighthouse?');
await page.getByRole('button', { name: 'Send message', exact: true }).click();
await page.locator('.fox-faq-note').waitFor();
assert.match(await page.locator('.fox-faq-note').innerText(), /saved portfolio answer/);
assert.match(await page.locator('.fox-assistant').innerText(), /Lighthouse/);
assert.equal(await page.locator('.fox-error').isVisible(), false);
await page.getByRole('button', { name: 'Reset chat', exact: true }).click();
const requests = [];
await page.route('**/api/chat', async route => {
  requests.push(route.request().postDataJSON());
  const body = [{ delta: 'Blair designed **Lighthouse** to support travelers. ' }, { delta: '[Explore Lighthouse](/project-1-lighthouse/). [IMAGE:lighthouse]' }].map(x => `data: ${JSON.stringify(x)}\r\n\r\n`).join('') + 'data: [DONE]\n\n';
  await route.fulfill({ status: 200, contentType: 'text/event-stream', body });
});
await page.locator('textarea').fill('What is Lighthouse?');
await page.getByRole('button', { name: 'Send message', exact: true }).click();
await page.locator('.fox-photo img').waitFor();
await page.waitForFunction(() => !document.querySelector('textarea').disabled);
assert.equal(requests[0].pageContext.page, 'home');
assert.equal(await page.locator('.fox-assistant strong').innerText(), 'Lighthouse');
await page.reload(); await page.locator('.fox-pet').click();
assert.equal(await page.locator('.fox-photo').count(), 1);
await page.getByRole('button', { name: 'Ask about this', exact: true }).click();
await page.getByRole('button', { name: 'Send message', exact: true }).click();
await page.waitForFunction(() => !document.querySelector('textarea').disabled);
assert.deepEqual(requests.at(-1).selectedPhotos, ['lighthouse']);
await page.getByRole('button', { name: 'Reset chat', exact: true }).click();
assert.equal(await page.locator('.fox-message').count(), 0);
await page.getByRole('button', { name: 'Close chat', exact: true }).click();
await page.evaluate(() => { const range = document.createRange(); range.selectNodeContents(document.querySelector('.hero h1')); const selection = getSelection(); selection.removeAllRanges(); selection.addRange(range); });
await page.locator('.fox-selection').click();
assert.equal(await page.locator('.fox-quote').isVisible(), true);
await page.locator('textarea').fill('Can you explain this?');
await page.getByRole('button', { name: 'Send message', exact: true }).click();
await page.waitForFunction(() => !document.querySelector('textarea').disabled);
assert.ok(requests.at(-1).context.length > 10);
await page.getByRole('button', { name: 'Reset chat', exact: true }).click();
// The mocked reply mentions Lighthouse, even for a general background question.
// That incidental mention must not create a project followup.
await page.locator('textarea').fill('What is Blair’s design background?');
await page.getByRole('button', { name: 'Send message', exact: true }).click();
await page.waitForFunction(() => !document.querySelector('textarea').disabled);
assert.doesNotMatch(await page.locator('.fox-suggestions').innerText(), /Lighthouse|HHI|this project/i);
await page.locator('textarea').fill('Tell me about HHI Concours.');
await page.getByRole('button', { name: 'Send message', exact: true }).click();
await page.waitForFunction(() => !document.querySelector('textarea').disabled);
assert.equal(await page.getByRole('button', { name: 'What did Blair learn from HHI?', exact: true }).count(), 1);
assert.doesNotMatch(await page.locator('.fox-suggestions').innerText(), /Lighthouse|this project/i);
await page.locator('textarea').fill('How can I get in touch with Blair?');
await page.getByRole('button', { name: 'Send message', exact: true }).click();
await page.waitForFunction(() => !document.querySelector('textarea').disabled);
assert.doesNotMatch(await page.locator('.fox-suggestions').innerText(), /Lighthouse|HHI|this project/i);
await page.getByRole('button', { name: 'Reset chat', exact: true }).click();
for (const [path, expected] of [['/about.html', 'Getting to know Blair'], ['/project-1-lighthouse/', 'Lighthouse'], ['/project-2-southerncrafted/', 'Southern Crafted'], ['/project-3-hhi/', 'HHI Concours'], ['/project-4-nalu/', 'Nalu']]) {
  await page.goto(base + path); await page.locator('.fox-pet').click();
  assert.ok((await page.locator('.fox-context').innerText()).includes(expected));
  await page.getByRole('button', { name: 'Reset chat', exact: true }).click();
}
await page.setViewportSize({ width: 390, height: 844 });
await page.goto(base + '/'); await page.locator('.fox-pet').click();
await page.screenshot({ path: 'qa/fox-phone-open.png' });
const mobile = await page.locator('.fox-panel').boundingBox();
assert.ok(mobile.x >= 0 && mobile.x + mobile.width <= 390 && mobile.y >= 0);
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.keyboard.press('Escape');
assert.equal(await page.locator('.fox-panel').isVisible(), false);
await page.screenshot({ path: 'qa/fox-phone-closed.png' });
const reduced = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
await reduced.clock.install();
await reduced.goto(base);
await reduced.locator('.fox-pet').waitFor();
await reduced.clock.fastForward(30000);
assert.equal(await reduced.locator('.fox-pet').getAttribute('data-pose'), 'seated');
await reduced.clock.fastForward(30_100);
assert.equal(await reduced.locator('.fox-pet').getAttribute('data-pose'), 'seated');
assert.equal(await reduced.locator('.fox-avatar').evaluate(svg => svg.animationsPaused()), true);
await reduced.keyboard.press('Shift');
assert.equal(await reduced.locator('.fox-pet').getAttribute('data-pose'), 'seated');
for (const path of ['/.env', '/server/knowledge.js', '/server/chat-handler.js', '/.git/config']) assert.equal((await page.request.get(base + path)).status(), 404);
assert.deepEqual(errors, []);
console.log('Browser checks passed: fixed seated fox, tail-only animation, chat, unavailable API, images, history, selection, all pages, phone and reduced motion.');
await browser.close();
