'use strict';
let focusGroup=state.hmws[0]?.id||null,spaceDown=false,spinTimer=null,pendingAddFace='user',lastNoteClick=null;
const axisInfo={impact:{x:'Effort',y:'Impact',left:'Less effort',right:'More effort',top:'High impact',bottom:'Low impact',labels:['Quick wins','Big bets','Nice to have','Reconsider'],subs:['Small effort, meaningful impact','Bigger commitments, bigger potential','Keep for a quieter moment','Rethink the investment']},novelty:{x:'Feasibility',y:'Novelty',left:'Harder to build',right:'Easier to build',top:'More original',bottom:'More familiar',labels:['Bold experiments','Fresh & doable','Park for now','Safe bets'],subs:['Test the key assumption','Original and within reach','Keep on the back burner','A reliable place to start']},value:{x:'Business value',y:'User value',left:'Lower business value',right:'Higher business value',top:'High user value',bottom:'Low user value',labels:['User delight','Win–win','Low priority','Business first'],subs:['Start with the people','Good for people and the product','Revisit another time','Consider the experience trade-off']}};
function renderCanvasBoard(){
 const v=$('#viewport');
 if(state.stage===2){
 if(!state.notes.length&&!state.hmws.length){v.innerHTML=emptyState('Every idea starts somewhere.','Add a thought, or frame a question to explore.','Add your first idea','add-first', 'Add a question','add-hmw');return}const {w,h}=boardSize();
 v.innerHTML=`<div class="world" id="world" style="width:${w}px;height:${h}px">${state.hmws.map((g,i)=>{const count=state.notes.filter(n=>n.group===g.id).length;return `<section class="hmw-group" style="left:${i*324}px;min-height:${Math.max(590,154+count*150)}px"><div class="hmw-meta"><span>HMW ${String(i+1).padStart(2,'0')}</span><span class="group-count">${count} ideas</span></div><h2 class="hmw-title">${esc(g.text)}</h2><button class="group-add" data-group-add="${g.id}">＋ Add an idea</button></section>`}).join('')}${state.notes.map(n=>noteMarkup({...n,...position(n)})).join('')}${selectionToolbar()}</div>`;
 }else{
 if(!state.notes.length){v.innerHTML=emptyState('A direction starts with an idea.','Add your ideas in Ideate, then bring them here to compare.','Go to Ideate','go-ideate');return}const a=axisInfo[state.axis];
 v.innerHTML=`<div class="world map-world" id="world"><div class="map-grid">${a.labels.map((l,i)=>`<div class="quadrant">${l}<span>${a.subs[i]}</span></div>`).join('')}</div><span class="axis-y">${a.y}</span><span class="axis-x">${a.x}</span><span class="axis-end" style="left:52px;bottom:10px">${a.left}</span><span class="axis-end" style="right:50px;bottom:10px">${a.right}</span><span class="axis-end" style="left:47px;top:3px">${a.top}</span><span class="axis-end" style="left:47px;bottom:39px">${a.bottom}</span>${state.notes.some(n=>!n.evaluations?.[state.axis])?'<div class="unrated-label">UNRATED IDEAS · Drag onto the map, or select one to rate it.</div>':''}${state.notes.map(n=>noteMarkup({...n,...position(n)},true)).join('')}${selectionToolbar()}</div>`;
 }
 applyTransform();bindCanvas();
}
function selectionToolbar(){const n=state.notes.find(n=>n.id===selected);if(!n)return '';const p=position(n);return `<div class="selection-tools" style="left:${p.x}px;top:${Math.max(0,p.y-45)}px"><button data-action="edit-note">${icon('pencil',12)} Edit</button><button data-action="vary" ${!aiReady?'disabled title="Connect Cube AI to explore variations"':''}>${icon('spark',12)} New angle</button><button data-action="merge">Combine</button><button data-action="delete-note" aria-label="Delete note">${icon('trash',13)}</button></div>`}
function suggestionMarkup(){if(!suggestion)return '';return `<div class="prompt-question">${esc(suggestion.question)}</div><div class="suggestion-card"><small>${faceBy(suggestion.face).label} · STARTER IDEA</small><p>${esc(suggestion.text)}</p><button class="btn small soft full" data-action="accept-suggestion">${icon('plus',13)}Add to board</button></div><p class="assistant-copy" style="font-size:11px;margin-top:10px">Why this angle: ${esc(suggestion.reason)}</p>`}
function setSidebarOpen(open,moveFocus=true){
 sidebarOpen=Boolean(open);
 if(sidebarOpen)updateWorkflowControls();
 const toggle=$('#navigation-toggle'),sidebar=$('#stage-sidebar'),backdrop=$('#sidebar-backdrop');
 if(!toggle||!sidebar||!backdrop)return;
 sidebar.hidden=!sidebarOpen;backdrop.hidden=!sidebarOpen;
 toggle.setAttribute('aria-expanded',String(sidebarOpen));toggle.setAttribute('aria-label',sidebarOpen?'Close navigation':'Open navigation');
 for(const region of ['#app > main','.topbar .brand','.header-project','.top-right']){const el=$(region);if(el)el.inert=sidebarOpen;}
 if(moveFocus){if(sidebarOpen)$('#stage-sidebar [aria-current="step"]')?.focus();else toggle.focus();}
}
function changeStage(i){if(!Number.isInteger(i)||i<0||i>3)return false;saveWorkflowDraft();const issue=workflowBlocker(i);if(issue){updateWorkflowControls();explainWorkflowBlocker(issue);return false}const fromSidebar=sidebarOpen;sidebarOpen=false;state.stage=i;selected=null;suggestion=null;spaceDown=false;save();render();if(fromSidebar)$('#navigation-toggle')?.focus();return true}
function saveContext(){if($('#goal')){state.goal=$('#goal').value;state.audience=$('#audience').value;save()}}
function createNote(faceId,text,groupId=focusGroup){const issue=workflowBlocker(2);if(issue)throw Error(issue.message);if(!faces.some(f=>f.id===faceId))throw Error('Unknown perspective');if(!text?.trim())throw Error('Write an idea first');if(!state.hmws.some(h=>h.id===groupId))groupId=null;snapshot();const n={id:'n'+Date.now()+Math.floor(Math.random()*1000),group:groupId,face:faceId,text:text.trim().slice(0,600),likes:0,evaluations:{},placed:false};state.notes.push(n);selected=n.id;state.stage=2;save();render();return n}
function modal(title,body,actions=''){const m=$('#modal');m.innerHTML=`<div class="modal-inner"><div class="modal-head"><h2>${title}</h2><button class="icon-btn" data-close aria-label="Close">${icon('close')}</button></div>${body}${actions?`<div class="modal-actions">${actions}</div>`:''}</div>`;m.showModal();m.onclick=e=>{if(e.target.closest('[data-close]')||e.target===m)m.close()};return m}
function editNote(id,faceId='user',groupId=focusGroup){const n=state.notes.find(n=>n.id===id);pendingAddFace=n?.face||faceId;const m=modal(n?'Make the idea a little clearer':'Catch a thought',`<label for="note-content">Your idea</label><textarea id="note-content" class="modal-field" maxlength="600" placeholder="Get it down. It doesn’t need to be perfect yet.">${esc(n?.text||'')}</textarea><label for="note-perspective">Perspective</label><select id="note-perspective" class="modal-field">${faces.map(f=>`<option value="${f.id}" ${f.id===pendingAddFace?'selected':''}>${f.label}</option>`).join('')}</select><label for="note-group">Related question</label><select id="note-group" class="modal-field"><option value="">No question — free on the board</option>${state.hmws.map(h=>`<option value="${h.id}" ${h.id===(n?.group||groupId)?'selected':''}>${esc(h.text)}</option>`).join('')}</select>`,`<button class="btn" data-close>Cancel</button><button class="btn primary" id="save-note">${n?'Save changes':'Add to board'}</button>`);$('#save-note').onclick=()=>{const text=$('#note-content').value.trim();if(!text){$('#note-content').focus();return}const f=$('#note-perspective').value,g=$('#note-group').value;if(n){snapshot();Object.assign(n,{text,face:f,group:g});save();render()}else createNote(f,text,g);m.close();toast(n?'Idea updated':'New idea added to your board')};setTimeout(()=>$('#note-content')?.focus(),30)}
function addHmw(){const issue=workflowBlocker(1);if(issue)return explainWorkflowBlocker(issue);const m=modal('Open up a new question',`<label for="hmw-new">How might we…</label><textarea id="hmw-new" class="modal-field" maxlength="160" placeholder="How might we…?"></textarea>`,`<button class="btn" data-close>Cancel</button><button class="btn primary" id="confirm-hmw">Add a question</button>`);$('#confirm-hmw').onclick=()=>{const text=$('#hmw-new').value.trim();if(!text)return $('#hmw-new').focus();snapshot();state.hmws.push({id:'h'+Date.now(),text});save();render();m.close();toast('A new question section is ready')};$('#hmw-new').focus()}
function undo(){if(!history.length)return toast('Nothing to undo yet');future.push(JSON.stringify(state));state=JSON.parse(history.pop());selected=null;save();render();toast('Undone')}
function redo(){if(!future.length)return toast('Nothing to redo yet');history.push(JSON.stringify(state));state=JSON.parse(future.pop());selected=null;save();render();toast('Redone')}
function deleteNote(){if(!selected)return;const id=selected;snapshot();state.notes=state.notes.filter(n=>n.id!==id);selected=null;save();render();toast('Note deleted · ⌘Z to undo')}
function removeHmw(id){const n=state.notes.filter(n=>n.group===id).length;const m=modal('Remove this question?',`<p>${n?`The ${n} ideas in this section will be kept on the board, under another question if one exists. `:'There are no ideas under this question yet.'}You can undo this change.</p>`,`<button class="btn" data-close>Cancel</button><button class="btn primary" id="confirm-remove-hmw">Remove question</button>`);$('#confirm-remove-hmw').onclick=()=>{snapshot();state.hmws=state.hmws.filter(h=>h.id!==id);state.notes.filter(n=>n.group===id).forEach(n=>{n.group=state.hmws[0]?.id||null;n.dx=0;n.dy=0});focusGroup=state.hmws[0]?.id||null;save();render();m.close()}}
function mergeNotes(){const n=state.notes.find(n=>n.id===selected);if(!n)return;if(state.notes.length<2)return toast('Add another idea before combining');const m=modal('Connect two ideas',`<p>${esc(n.text)}</p><label for="merge-target">Which idea should it connect with?</label><select id="merge-target" class="modal-field">${state.notes.filter(m=>m.id!==n.id).map(m=>`<option value="${m.id}">${esc(m.text)}</option>`).join('')}</select><p style="margin-top:14px;font-size:12px">This creates a new note and keeps both original ideas.</p>`,`<button class="btn" data-close>Cancel</button><button class="btn primary" id="confirm-merge">Create a combined idea</button>`);$('#confirm-merge').onclick=()=>{const other=state.notes.find(m=>m.id===$('#merge-target').value);createNote(n.face,n.text+' And: '+other.text,n.group);m.close();toast('Combined idea added. Originals kept.')}}
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function action(a){switch(a){case'toggle-navigation':setSidebarOpen(!sidebarOpen);break;case'close-navigation':setSidebarOpen(false);break;case'toggle-panel':panelOpen=!panelOpen;render();break;case'undo':undo();break;case'redo':redo();break;case'help':showHelp();break;case'share':showShare();break;case'summary':showSummary();break;case'add-hmw':addHmw();break;case'add-text':editNote(null,'constraint');break;case'add-first':editNote(null,'user');break;case'go-ideate':changeStage(2);break;case'boards':showBoards();break;case'new-board':newBoard();break;case'upload':$('#file-input').click();break;case'edit-note':editNote(selected);break;case'delete-note':deleteNote();break;case'merge':mergeNotes();break;case'counter':ask('Challenge this idea');break;case'vary':panelOpen=true;face=faces[(faces.findIndex(f=>f.id===state.notes.find(n=>n.id===selected)?.face)+1)%6].id;render();spin();break;case'wildcard':panelOpen=true;face='wildcard';render();spin();break;case'spin':spin();break;case'accept-suggestion':if(suggestion){const s={...suggestion};const n=createNote(s.face,s.text,s.group);n.author='Cube';suggestion=null;save();render();toast('Starter idea added. Double-click to make it your own.')}break;case'cluster':snapshot();state.notes.sort((a,b)=>faces.findIndex(f=>f.id===a.face)-faces.findIndex(f=>f.id===b.face));state.notes.forEach(n=>{n.dx=0;n.dy=0});save();renderBoard();fit();toast('Ideas organized by perspective within each question');break;case'place':placeNotes();break;case'lock':{const n=state.notes.find(n=>n.id===selected);if(n){snapshot();n.locked=!n.locked;save();renderPanel();toast(n.locked?'Position locked':'Position unlocked')}break}case'rescore':placeNotes(selected);break;case'fit':fit();break;case'zoom-in':changeZoom(zoom*1.15);break;case'zoom-out':changeZoom(zoom/1.15);break}}
function changeZoom(next,cx,cy){if(state.stage<2)return;const v=$('#viewport');if(!$('#world'))return;cx??=v.clientWidth/2;cy??=v.clientHeight/2;next=Math.max(.25,Math.min(2,next));pan.x=cx-(cx-pan.x)*next/zoom;pan.y=cy-(cy-pan.y)*next/zoom;zoom=next;applyTransform()}
function bind(){
 $('#app').onclick=e=>{const t=e.target.closest('button,[data-note]');if(!t)return;if(t.dataset.stage!==undefined)return changeStage(Number(t.dataset.stage));if(t.dataset.face){face=t.dataset.face;suggestion=null;renderPanel();return}if(t.dataset.add)return editNote(null,t.dataset.add);if(t.dataset.groupAdd){focusGroup=t.dataset.groupAdd;return editNote(null,'user',focusGroup)}if(t.dataset.like){snapshot();const n=state.notes.find(n=>n.id===t.dataset.like);n.liked=!n.liked;n.likes=Math.max(0,(n.likes||0)+(n.liked?1:-1));save();renderBoard();return}if(t.dataset.tool){tool=t.dataset.tool;$('.board-viewport').classList.toggle('pan-mode',tool==='hand');document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));return}if(t.dataset.removeHmw)return removeHmw(t.dataset.removeHmw);if(t.dataset.removeFile!==undefined){snapshot();state.attachments.splice(Number(t.dataset.removeFile),1);save();render();return}if(t.dataset.action)return action(t.dataset.action)};
 $('#app').ondblclick=e=>{const n=e.target.closest('[data-note]');if(n&&!e.target.closest('button')&&!$('#modal').open)editNote(n.dataset.note)};
 $('#app').onchange=e=>{if(e.target.matches('[data-hmw]')){const text=e.target.value.trim();snapshot();state.hmws.find(h=>h.id===e.target.dataset.hmw).text=text;save();updateWorkflowControls()}if(e.target.id==='axis'){snapshot();state.axis=e.target.value;selected=null;save();renderBoard();renderPanel()}if(e.target.id==='goal'||e.target.id==='audience'){snapshot();saveContext();if($('#brief-goal'))$('#brief-goal').textContent=state.goal;if($('#brief-audience'))$('#brief-audience').textContent=state.audience}};
 if($('#ask-form'))$('#ask-form').onsubmit=e=>{e.preventDefault();const input=$('#ask-input'),q=input.value;input.value='';ask(q)};
 $('#file-input').onchange=e=>handleFiles(e.target.files).catch(()=>toast('Could not read the file. Please try again.'));
 if($('#context-form'))$('#context-form').onsubmit=e=>{e.preventDefault();saveContext();if(!state.goal.trim())return toast('Add your goal first');changeStage(1);toast('Your brief is ready. Add a question to begin.')};
 const zone=$('.upload-zone');if(zone){zone.ondragover=e=>{e.preventDefault();zone.style.borderColor='#5059ed'};zone.ondragleave=()=>zone.style.borderColor='';zone.ondrop=e=>{e.preventDefault();handleFiles(e.dataTransfer.files)}}
}
function bindCanvas(){
 if(state.stage<2)return;const v=$('#viewport');if(!$('#world'))return;v.classList.toggle('pan-mode',tool==='hand');let drag=null,pointers=new Map(),pinch=null;
 v.onpointerdown=e=>{if(e.target.closest('button,.selection-tools'))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){drag=null;const p=[...pointers.values()];pinch={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),zoom};return}const el=e.target.closest('[data-note]');const n=el&&state.notes.find(n=>n.id===el.dataset.note);const movingCanvas=tool==='hand'||spaceDown||!n;if(n&&!movingCanvas&&n.locked&&state.stage===3){selected=n.id;renderBoard();renderPanel();toast('This position is locked. Unlock it in the Cube panel first.');return}if(n&&!movingCanvas){selected=n.id;focusGroup=n.group;document.querySelectorAll('[data-note]').forEach(x=>x.classList.toggle('selected',x.dataset.note===n.id));renderPanel()}drag={id:e.pointerId,n:movingCanvas?null:n,el,startX:e.clientX,startY:e.clientY,pan:{...pan},pos:n?position(n):null,changed:false};v.setPointerCapture(e.pointerId)};
 v.onpointermove=e=>{if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&pointers.size===2){const p=[...pointers.values()],r=v.getBoundingClientRect();changeZoom(pinch.zoom*Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)/pinch.distance,(p[0].x+p[1].x)/2-r.left,(p[0].y+p[1].y)/2-r.top);return}if(!drag)return;const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(!drag.changed&&Math.hypot(dx,dy)<4)return;if(!drag.changed){drag.changed=true;if(drag.n)snapshot()}if(drag.n){drag.el.classList.add('dragging');drag.el.style.left=drag.pos.x+dx/zoom+'px';drag.el.style.top=drag.pos.y+dy/zoom+'px'}else{pan.x=drag.pan.x+dx;pan.y=drag.pan.y+dy;applyTransform()}};
 function finish(e){pointers.delete(e.pointerId);if(pointers.size<2)pinch=null;if(!drag)return;const d=drag;drag=null;if(d.n&&d.changed){const dx=(e.clientX-d.startX)/zoom,dy=(e.clientY-d.startY)/zoom;if(state.stage===3){d.n.mx=Math.max(44,Math.min(708,d.pos.x+dx));d.n.my=Math.max(70,Math.min(445,d.pos.y+dy));updateScores(d.n)}else{const left=d.pos.x+dx,top=d.pos.y+dy,gi=Math.max(0,Math.min(state.hmws.length-1,Math.floor((left+100)/324))),newGroup=state.hmws.length&&top<boardSize().groupBottom?state.hmws[gi]?.id||null:null;if(newGroup!==d.n.group){d.n.group=newGroup;d.n.dx=0;d.n.dy=0}else{d.n.dx=(d.n.dx||0)+dx;d.n.dy=(d.n.dy||0)+dy}}save();renderBoard();renderPanel()}else if(d.n){const double=lastNoteClick?.id===d.n.id&&Date.now()-lastNoteClick.time<400;lastNoteClick={id:d.n.id,time:Date.now()};renderBoard();renderPanel();if(double){lastNoteClick=null;editNote(d.n.id)}}else if(!d.changed){selected=null;renderBoard();renderPanel()}}
 v.onpointerup=finish;v.onpointercancel=e=>{pointers.delete(e.pointerId);pinch=null;drag=null;renderBoard()};
 v.onwheel=e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){const r=v.getBoundingClientRect();changeZoom(zoom*Math.exp(-e.deltaY*.004),e.clientX-r.left,e.clientY-r.top)}else{pan.x-=e.deltaX;pan.y-=e.deltaY;applyTransform()}};
}
window.addEventListener('keydown',e=>{if(sidebarOpen){if(e.key==='Escape'){e.preventDefault();setSidebarOpen(false)}else if(e.key==='Tab'){const items=[$('#navigation-toggle'),...document.querySelectorAll('#stage-sidebar [data-stage]:not(:disabled)')],index=items.indexOf(document.activeElement);e.preventDefault();items[(index+(e.shiftKey?-1:1)+items.length)%items.length]?.focus()}return}const editing=e.target.matches('input,textarea,select,[contenteditable]')||e.target.isContentEditable;if(e.key==='Escape'&&!$('#modal').open&&state.stage>=2){selected=null;renderBoard();renderPanel()}if(editing||$('#modal').open||state.stage===0)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if(state.stage<2)return;if(!e.repeat&&!e.metaKey&&!e.ctrlKey&&!e.altKey&&e.key.toLowerCase()==='q'){e.preventDefault();action('toggle-panel');return}if(e.code==='Space'){e.preventDefault();spaceDown=true;$('#viewport').classList.add('pan-mode')}if(!e.metaKey&&!e.ctrlKey&&(e.key==='v'||e.key==='h')){tool=e.key==='v'?'cursor':'hand';document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#viewport').classList.toggle('pan-mode',tool==='hand')}if((e.key==='Delete'||e.key==='Backspace')&&selected){e.preventDefault();deleteNote()}if(e.key==='Enter'&&(selected||e.target.dataset.note)){e.preventDefault();editNote(e.target.dataset.note||selected)}});
window.addEventListener('keyup',e=>{if(e.code==='Space'&&state.stage>=2){spaceDown=false;$('#viewport')?.classList.toggle('pan-mode',tool==='hand')}});
window.addEventListener('blur',()=>spaceDown=false);
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(fit,150)});
function registerTools(){const c=document.modelContext;if(!c?.registerTool)return;const lifecycle=new AbortController();const definitions=[{name:'read_cube_board',title:'Read the Cube board',description:'Read the current project, questions and ideas without changing the board.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({stage:state.stage,goal:state.goal,audience:state.audience,questions:state.hmws,ideas:state.notes.map(n=>({id:n.id,text:n.text,face:n.face,group:n.group}))})},{name:'add_cube_idea',title:'Add a Cube idea',description:'Create a sticky note in the current Cube board using the same action as the visible add note dialog.',inputSchema:{type:'object',properties:{text:{type:'string'},face:{type:'string',enum:faces.map(f=>f.id)},groupId:{type:'string'}},required:['text','face'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:input=>{if(!input||typeof input.text!=='string'||!input.text.trim()||input.text.length>600||!faces.some(f=>f.id===input.face)||input.groupId&&!state.hmws.some(h=>h.id===input.groupId))throw Error('Invalid idea input');const n=createNote(input.face,input.text,input.groupId||state.hmws[0]?.id||null);return {id:n.id,text:n.text,face:n.face,group:n.group}}}];definitions.forEach(t=>{try{Promise.resolve(c.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch(e){}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
