'use strict';
// The shared workspace starts empty, or uses the demo route’s example content.
let aiReady=false,aiBusy=false;
function emptyState(title,copy,label,action,secondary,secondAction){return `<div class="workspace-empty"><div class="empty-symbol">${icon('section',32)}</div><h2>${title}</h2><p>${copy}</p><div class="empty-actions"><button class="btn primary" data-action="${action}">${icon('plus',15)}${label}</button>${secondary?`<button class="btn" data-action="${secondAction}">${secondary}</button>`:''}</div></div>`}
function renderBoard(){
 const v=$('#viewport');
 if(state.stage===0){v.innerHTML=`<div class="context-setup"><div class="setup-heading"><h1>What are we exploring today?</h1></div><form class="context-form" id="context-form"><label for="board-title">Project name <span class="optional">optional</span></label><input id="board-title" value="${esc(state.title==='Untitled board'?'':state.title)}" maxlength="80" placeholder="Give your project a name" autocomplete="off"><label for="goal">What are you trying to solve?</label><textarea id="goal" required maxlength="800" placeholder="Describe your challenge or the outcome you’re working toward.">${esc(state.goal)}</textarea><label for="audience">Who are you designing for? <span class="optional">optional</span></label><textarea id="audience" maxlength="500" placeholder="Who are they, and what matters to them?">${esc(state.audience)}</textarea><label class="reference-label">Research & references <span class="optional">optional</span></label><button type="button" class="upload-zone" data-action="upload">${icon('share',21)}<div><strong>Drop files here, or browse</strong><span>Images or PDFs · Up to 5 MB per file</span></div></button><div class="attachments">${state.attachments.map((a,i)=>`<span class="attachment"><button type="button" data-open-file="${i}" title="Open attachment">${icon('file',12)} ${esc(a.name)}</button><button type="button" data-remove-file="${i}" aria-label="Remove ${esc(a.name)}">×</button></span>`).join('')}</div><div class="setup-footer"><button class="btn primary workflow-next" id="context-continue" type="submit" aria-describedby="step-requirement" ${stageGateAttributes(1)}>Continue to Decompose</button></div><p class="context-footer-notes"><span class="step-requirement" id="step-requirement" role="status" aria-live="polite"></span><span class="setup-save-note">You can come back and refine this anytime.</span></p></form></div>`;return;
 }else if(state.stage===1){v.innerHTML=`<div class="context-setup decompose-setup"><div class="setup-heading"><h1>Big challenge. Better questions.</h1></div>${state.goal?`<section class="challenge-summary" aria-labelledby="challenge-title"><div class="challenge-heading"><h2 id="challenge-title">Design challenge</h2><button class="text-button" data-stage="0">Edit context</button></div><p>${esc(state.goal)}</p></section>`:''}${state.hmws.length?`<div class="hmw-list">${state.hmws.map((h,i)=>`<div class="hmw-row"><span class="row-no">${String(i+1).padStart(2,'0')}</span><textarea data-hmw="${h.id}" aria-label="Question ${i+1}" required rows="2" maxlength="160">${esc(h.text)}</textarea><button class="icon-btn" data-remove-hmw="${h.id}" aria-label="Remove question ${i+1}">${icon('trash',15)}</button></div>`).join('')}</div><button class="btn add-question" data-action="add-hmw">${icon('plus',14)}Add a question</button>`:emptyState('Find a question worth asking.','Start with “How might we…” and leave room for more than one answer.','Write a question','add-hmw')}<div class="ai-inline"><button class="btn soft" data-live-action="decompose" ${!aiReady||aiBusy?'disabled':''}>${icon('spark',14)}Explore questions with Cube</button>${!aiReady?'<span>AI is not connected yet.</span>':''}</div><div class="setup-footer decompose-footer"><button class="text-button" data-stage="0">Back to Context</button><button class="btn primary workflow-next" data-stage="2" aria-describedby="step-requirement" ${stageGateAttributes(2)}>Continue to Ideate</button></div><p class="step-requirement" id="step-requirement" role="status" aria-live="polite"></p></div>`;return;
 }else renderCanvasBoard();
 const world=$('#world');if(world){const size=boardSize();world.style.width=size.w+'px';world.style.height=size.h+'px'}applyTransform();bindCanvas();
}
function boardSize(){const count=Math.max(0,...state.hmws.map(h=>state.notes.filter(n=>n.group===h.id).length)),groupBottom=state.hmws.length?Math.max(600,160+count*150):0,loose=state.notes.filter(n=>!state.hmws.some(h=>h.id===n.group)).length;if(state.stage===3)return {w:930,h:state.notes.some(n=>!n.evaluations?.[state.axis])?760+Math.ceil(state.notes.filter(n=>!n.evaluations?.[state.axis]).length/4)*95:610};return {w:Math.max(960,state.hmws.length*324-12),h:Math.max(610,groupBottom+Math.ceil(loose/3)*160),groupBottom}}
function position(n){if(state.stage===3){const s=n.evaluations?.[state.axis];if(s)return {x:s.mx??60+(s.x-1)/9*648,y:s.my??70+(10-s.y)/9*400};const i=state.notes.filter(m=>!m.evaluations?.[state.axis]).findIndex(m=>m.id===n.id);return {x:52+(i%4)*208,y:618+Math.floor(i/4)*86}}const index=state.hmws.findIndex(h=>h.id===n.group);if(index<0){const i=state.notes.filter(m=>!state.hmws.some(h=>h.id===m.group)).findIndex(m=>m.id===n.id);return {x:(i%3)*285+24+(n.dx||0),y:(state.hmws.length?boardSize().groupBottom:15)+Math.floor(i/3)*160+(n.dy||0)}}return {x:index*324+21+(n.dx||0),y:121+state.notes.filter(m=>m.group===n.group).findIndex(m=>m.id===n.id)*150+(n.dy||0)}}
function fit(){if(state.stage<2)return;const v=$('#viewport'),w=$('#world');if(!v||!w)return;const size=boardSize();zoom=Math.max(innerWidth<590?.62:.65,Math.min(1,(v.clientWidth-12)/size.w,(v.clientHeight-10)/size.h));pan={x:Math.max(0,(v.clientWidth-size.w*zoom)/2),y:5};applyTransform()}
function renderPanel(){if(state.stage<2)return;const input=$('#ask-input'),send=$('#ask-form button');if(input){input.disabled=!aiReady||aiBusy;input.placeholder=aiReady?'Ask Cube anything…':'Cube AI is not connected';}if(send)send.disabled=!aiReady||aiBusy;const p=$('#panel-content'),n=state.notes.find(n=>n.id===selected),a=axisInfo[state.axis];
 if(state.stage===3){const s=n?.evaluations?.[state.axis];p.innerHTML=n?`<div class="focus-caption">${s?'YOUR JUDGMENT':'NOT RATED YET'}</div><div class="assistant-intro">Make your own call.</div><p class="assistant-copy">${esc(n.text)}</p><div class="rating-controls"><label for="rating-y">${a.y}<strong id="rating-y-value">${s?.y??'—'}</strong></label><input type="range" id="rating-y" data-rating="y" min="1" max="10" value="${s?.y??5}" aria-label="${a.y}"><label for="rating-x">${a.x}<strong id="rating-x-value">${s?.x??'—'}</strong></label><input type="range" id="rating-x" data-rating="x" min="1" max="10" value="${s?.x??5}" aria-label="${a.x}"><button class="btn soft full" data-live-action="rate" style="margin-top:12px">${s?'Update placement':'Place on the map'}</button></div><label class="panel-label" for="rating-reason">Why here?</label><textarea class="reason-input" id="rating-reason" placeholder="Capture the reasoning behind your choice." maxlength="800">${esc(s?.reason||'')}</textarea><button class="btn full" data-action="lock" style="margin-top:15px">${icon('lock',14)}${n.locked?'Unlock position':'Lock position'}</button><p class="assistant-copy" style="margin-top:16px;font-size:12px">${s?'Drag to adjust, or use the sliders.':'Nothing has been scored for you. Choose the ratings you think fit.'}</p>`:`<div class="assistant-intro">A little perspective<br>on what comes next.</div><p class="assistant-copy">Select an idea to rate it. Drag it onto the map, and capture your reasons as you go.</p><div class="score-box"><strong>${a.y} × ${a.x}</strong><p class="assistant-copy" style="margin-top:10px">${state.notes.filter(n=>n.evaluations?.[state.axis]).length} of ${state.notes.length} ideas rated.</p></div><div class="map-idea-list">${state.notes.map(item=>`<button data-select-note="${item.id}"><span style="background:${faceBy(item.face).color}"></span>${esc(item.text)}</button>`).join('')}</div><button class="btn full" data-action="summary" ${!state.notes.length?'disabled':''}>${icon('download',15)}Create direction summary</button>`;return}
 const counts=faces.map(f=>state.notes.filter(n=>n.face===f.id).length),covered=counts.filter(Boolean).length;
 p.innerHTML=`<div class="assistant-intro">${state.stage===0?'A little context.<br>A clearer starting point.':state.stage===1?'Good questions<br>open up possibilities.':n?'Give this idea<br>another perspective.':'Six sides.<br>Room for your ideas.'}</div><p class="assistant-copy">${state.stage===0?'Describe your goal and audience, or jump into an empty canvas.':state.stage===1?'Write a question broad enough to invite different answers, and focused enough to act on.':n?esc(n.text):'Choose a perspective, then add your own thoughts to the board.'}</p>${state.stage===2?`<div class="panel-label"><span>PERSPECTIVES</span><strong>${covered} / 6 explored</strong></div><div class="perspectives">${faces.map((f,i)=>`<button class="face ${face===f.id?'active':''}" data-face="${f.id}" aria-pressed="${face===f.id}"><span class="face-dot" style="background:${f.color}">${icon(f.icon,14)}</span><span>${f.label}</span><span class="count">${counts[i]} ideas</span></button>`).join('')}</div><button class="btn full" style="margin-top:14px" data-add="${face}">${icon('plus',14)}Add a ${faceBy(face).label} idea</button><button class="btn primary full spin-btn" data-action="spin" ${!aiReady||aiBusy?'disabled':''}>${icon('rotate',16)}Spin the Cube</button><div id="suggestion">${suggestionMarkup()}</div>${state.notes.length?`<div class="coverage"><div class="coverage-head"><span>Perspective coverage</span><strong>${covered} / 6</strong></div><div class="coverage-bars">${faces.map((f,i)=>`<span style="background:${counts[i]?f.color:'#edf0f5'}"></span>`).join('')}</div></div>`:''}`:''}${!aiReady?'<div class="ai-connection-note">Cube AI is not connected yet. Your board is ready to use.</div>':''}<div id="chat-log">${chat.map(c=>`<div class="chat-question">${esc(c.q)}</div><div class="chat-response">${esc(c.a)}</div>`).join('')}</div>`;

}
function syncProjectTitleInputs(){
 const value=state.title==='Untitled board'?'':state.title;
 for(const selector of ['#header-project-title','#board-title']){const input=$(selector);if(input)input.value=value;}
 const label=$('#project-title-label');if(label){label.textContent=value||'Untitled project';label.title=label.textContent;label.setAttribute('aria-label','Rename project: '+label.textContent);}
}
function saveProjectTitle(value){const title=value.trim().slice(0,80)||'Untitled board';if(title!==state.title){snapshot();state.title=title;save();}syncProjectTitleInputs();}
function saveContext(){if($('#goal')){state.goal=$('#goal').value;state.audience=$('#audience').value;const t=$('#board-title');if(t)state.title=t.value.trim()||'Untitled board';save();syncProjectTitleInputs();}}
function scoreFor(n){return n.evaluations?.[state.axis]||{x:null,y:null}}
function reasonFor(n){return n.evaluations?.[state.axis]?.reason||'No reasoning added yet.'}
function placeNotes(){const rated=state.notes.filter(n=>n.evaluations?.[state.axis]);if(!rated.length){toast('Select an idea and rate it first.');return}snapshot();for(const n of rated){if(n.locked)continue;const s=n.evaluations[state.axis];s.mx=60+(s.x-1)/9*648;s.my=70+(10-s.y)/9*400}save();renderBoard();toast('Placed using your ratings. Locked ideas stayed in place.')}
function updateScores(n){n.evaluations??={};const current=n.evaluations[state.axis]||{};n.evaluations[state.axis]={...current,x:Math.max(1,Math.min(10,Math.round((n.mx-60)/648*9)+1)),y:Math.max(1,Math.min(10,10-Math.round((n.my-70)/400*9))),mx:n.mx,my:n.my,source:'manual'};n.moved=true;n.placed=false;delete n.mx;delete n.my}
function rateSelected(){const n=state.notes.find(n=>n.id===selected);if(!n)return;if(n.locked)return toast('Unlock this idea before changing its position.');snapshot();const x=Number($('#rating-x').value),y=Number($('#rating-y').value);n.evaluations??={};n.evaluations[state.axis]={x,y,reason:$('#rating-reason').value.trim(),source:'manual',mx:60+(x-1)/9*648,my:70+(10-y)/9*400};save();renderBoard();renderPanel();toast('Placed using your ratings.')}
function boardHasContent(board){
 return !!board&&(hasContent(board.goal)||hasContent(board.audience)||(hasContent(board.title)&&!['Untitled board','Untitled project'].includes(board.title.trim()))||!!board.hmws?.length||!!board.notes?.length||!!board.attachments?.length);
}
function captureBoardDraft(){
 const draft=workflowDraft();state.goal=draft.goal;state.audience=draft.audience;state.hmws=draft.hmws;
 if(state.stage===0&&$('#board-title'))state.title=$('#board-title').value.trim().slice(0,80)||'Untitled board';
 // Opening the list must not recreate an empty board after its deletion.
 if(boardHasContent(state)||boardIndex.some(b=>b.id===state.id))save();
 syncProjectTitleInputs();
}
function showBoards(captureDraft=true){
 if(captureDraft)captureBoardDraft();
 const m=modal('Your boards',`<label for="rename-board">Board name</label><div class="rename-row"><input class="modal-field" id="rename-board" value="${esc(state.title)}" maxlength="80"><button class="btn" id="rename-save">Save</button></div><div class="recent-boards">${boardIndex.map(b=>`<div class="recent-board-row"><button class="recent-board" data-open-board="${esc(b.id)}"><span>${esc(b.title)}</span><small>${new Date(b.updatedAt).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></button><button class="icon-btn delete-board" data-delete-board="${esc(b.id)}" title="Delete board" aria-label="Delete ${esc(b.title)}">${icon('trash',16)}</button></div>`).join('')||'<p class="boards-empty">No saved boards yet.</p>'}</div><p class="small muted">Boards are saved on this device. Export a copy to take one with you.</p><a class="demo-link" href="../prototype/" target="_blank" rel="noopener">Open the blank prototype</a>`,`<button class="btn primary" id="new-blank">${icon('plus',14)}New blank board</button>`);
 m.oncancel=null;
 $('#rename-save').onclick=()=>{snapshot();state.title=$('#rename-board').value.trim()||'Untitled board';save();render();m.close()};
 $('#new-blank').onclick=()=>{newBoard();m.close()};
 const baseClick=m.onclick;m.onclick=e=>{
  const remove=e.target.closest('[data-delete-board]');if(remove){requestDeleteBoard(remove.dataset.deleteBoard);return;}
  baseClick(e);const b=e.target.closest('[data-open-board]');if(!b)return;
  try{const data=JSON.parse(localStorage.getItem(storageKeys.board(b.dataset.openBoard)));validateBoard({format:'cube-v2',board:data});state=data;history=[];future=[];selected=null;suggestion=null;focusGroup=state.hmws[0]?.id||null;save();render();m.close()}catch{toast('Could not open this board. Your current board is safe.')}
 };
}
function requestDeleteBoard(id){
 const entry=boardIndex.find(b=>b.id===id);if(!entry)return;
 let needsConfirmation=true;
 try{const board=id===state.id?state:JSON.parse(localStorage.getItem(storageKeys.board(id)));needsConfirmation=boardHasContent(board);}catch{}
 if(!needsConfirmation){deleteSavedBoard(id);return;}
 const m=modal('Delete board?',`<p>Delete <strong class="delete-board-name">${esc(entry.title)}</strong> and all of its content? This cannot be undone.</p>`,`<button class="btn" id="cancel-delete-board">Cancel</button><button class="btn danger" id="confirm-delete-board">${icon('trash',15)}Delete board</button>`);
 const cancel=()=>{showBoards(false);[...document.querySelectorAll('[data-delete-board]')].find(b=>b.dataset.deleteBoard===id)?.focus();};
 $('#cancel-delete-board').onclick=cancel;
 $('#confirm-delete-board').onclick=()=>deleteSavedBoard(id);
 m.oncancel=e=>{e.preventDefault();cancel();};
 m.onclick=e=>{if(e.target.closest('[data-close]')||e.target===m)cancel();};
 $('#cancel-delete-board').focus();
}
function deleteSavedBoard(id){
 if(!boardIndex.some(b=>b.id===id))return;
 const deletingCurrent=id===state.id,nextIndex=boardIndex.filter(b=>b.id!==id);
 let nextBoard=null;
 if(deletingCurrent){
  for(const entry of nextIndex){try{const data=JSON.parse(localStorage.getItem(storageKeys.board(entry.id)));validateBoard({format:'cube-v2',board:data});nextBoard=data;break;}catch{}}
 }
 let previousIndex,previousActive;
 try{
  previousIndex=localStorage.getItem(storageKeys.index);previousActive=localStorage.getItem(storageKeys.active);
  localStorage.setItem(storageKeys.index,JSON.stringify(nextIndex));
  if(deletingCurrent){if(nextBoard)localStorage.setItem(storageKeys.active,nextBoard.id);else localStorage.removeItem(storageKeys.active);}
  // Remove the data last so a failed metadata update cannot lose the board.
  localStorage.removeItem(storageKeys.board(id));
 }catch{
  try{if(previousIndex!==undefined){if(previousIndex===null)localStorage.removeItem(storageKeys.index);else localStorage.setItem(storageKeys.index,previousIndex);}if(previousActive!==undefined){if(previousActive===null)localStorage.removeItem(storageKeys.active);else localStorage.setItem(storageKeys.active,previousActive);}}catch{}
  toast('Could not delete this board. Please try again.');return;
 }
 boardIndex=nextIndex;
 if(deletingCurrent){state=nextBoard||blankBoard();history=[];future=[];selected=null;suggestion=null;chat=[];focusGroup=state.hmws[0]?.id||null;sidebarOpen=false;spaceDown=false;render();}
 showBoards(false);toast('Board deleted.');$('#new-blank').focus();
}

function newBoard(){if(state.goal||state.audience||state.notes.length||state.hmws.length)save();state=blankBoard();selected=null;suggestion=null;chat=[];history=[];future=[];focusGroup=null;save();render();toast('A fresh board, just for you.')}
function showSummary(){if(!state.notes.length){toast('Add an idea before exporting a summary.');return}const a=axisInfo[state.axis],rated=state.notes.filter(n=>n.evaluations?.[state.axis]),priorities=rated.filter(n=>{const s=scoreFor(n);return s.y>=6&&(state.axis==='impact'?s.x<=5:s.x>=6)}),unrated=state.notes.filter(n=>!n.evaluations?.[state.axis]);modal('Your direction summary',`<div class="summary-body"><h3>${esc(state.title)}</h3>${state.goal?`<p style="margin-top:12px">${esc(state.goal)}</p>`:''}<div class="panel-label">${priorities.length?'IDEAS TO EXPLORE FIRST':'YOUR IDEAS'}</div>${(priorities.length?priorities:state.notes).map((n,i)=>`<div class="summary-item">${i+1}. ${esc(n.text)}<small>${faceBy(n.face).label}${n.evaluations?.[state.axis]?` · ${a.y} ${scoreFor(n).y}/10 · ${a.x} ${scoreFor(n).x}/10`:' · Not rated'}</small>${n.evaluations?.[state.axis]?.reason?`<p class="small muted">${esc(n.evaluations[state.axis].reason)}</p>`:''}</div>`).join('')}<p style="font-size:12px;margin-top:18px">${unrated.length} unrated ideas. Placements and reasoning reflect your own judgments.</p></div>`,`<button class="btn" data-close>Keep exploring</button><button class="btn primary" id="download-summary">${icon('download',15)}Download summary</button>`);$('#download-summary').onclick=()=>{const text=`# ${state.title}\n\n## Goal\n${state.goal||'Not specified'}\n\n## Audience\n${state.audience||'Not specified'}\n\n## Questions\n${state.hmws.map(h=>'- '+h.text).join('\n')||'No questions added.'}\n\n## Ideas\n${state.notes.map((n,i)=>`${i+1}. ${n.text}\n   Perspective: ${faceBy(n.face).label}\n   ${n.evaluations?.[state.axis]?`${a.y}: ${scoreFor(n).y}/10; ${a.x}: ${scoreFor(n).x}/10\n   Reason: ${reasonFor(n)}`:'Not rated'}`).join('\n\n')}\n\nAll scores are user-provided.\n`;download('Cube-AI-summary.md',text,'text/markdown;charset=utf-8');toast('Summary downloaded.')};}
function showShare(){const m=modal('Share your thinking',`<p>Your board is saved on this device. Send someone a board file so they can import a copy and continue working.</p><button class="btn full" id="export-board">${icon('download',16)}Export board file</button><button class="btn full" id="import-board" style="margin-top:10px">${icon('share',16)}Import a board file</button><input id="import-input" type="file" accept="application/json,.json" hidden><div class="brief-line"></div><button class="btn soft full" id="copy-link">${icon('link',14)}Copy app link</button><p class="small muted" style="margin:10px 0 0">The app link opens a new workspace for other visitors. It does not share your private board. Live collaboration is not available.</p>`);$('#export-board').onclick=()=>{download('Cube-AI-board.json',JSON.stringify({format:'cube-v2',board:state},null,2),'application/json');toast('Board exported, including your attachments.')};$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(new URL('./', location.href).href);toast('App link copied.')}catch{toast('Copy the address from your browser to share the app.')}};$('#import-board').onclick=()=>$('#import-input').click();$('#import-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>12*1024*1024)throw Error('File is too large.');const d=JSON.parse(await file.text());validateBoard(d);if(state.goal||state.notes.length)save();state=normalizeBoard(d.board);history=[];future=[];selected=null;focusGroup=state.hmws[0]?.id||null;save();render();m.close();toast('Imported as a new board.')}catch(e){toast(e.message)}}}
function validateBoard(d){const b=d?.board;if(!['cube-v1','cube-v2'].includes(d?.format)||!b||!Array.isArray(b.hmws)||!Array.isArray(b.notes))throw Error('Choose a valid Cube.AI board file.');if(b.hmws.length>30||b.notes.length>300)throw Error('This board is too large.');if(typeof b.goal!=='string'||typeof b.audience!=='string'||b.hmws.some(h=>typeof h.id!=='string'||typeof h.text!=='string')||b.notes.some(n=>typeof n.text!=='string'||!faces.some(f=>f.id===n.face)))throw Error('The board is incomplete.');if(b.attachments&&!Array.isArray(b.attachments))throw Error('Invalid attachments.')}
function normalizeBoard(b){const hmws=b.hmws.map((h,i)=>({id:'h'+i,text:h.text.slice(0,160)}));return {...blankBoard(),goal:b.goal.slice(0,800),audience:b.audience.slice(0,500),title:typeof b.title==='string'?b.title.slice(0,80):'Imported board',stage:[0,1,2,3].includes(b.stage)?b.stage:2,axis:axisInfo[b.axis]?b.axis:'impact',hmws,notes:b.notes.map((n,i)=>{const evaluations={};for(const key of Object.keys(axisInfo)){const e=n.evaluations?.[key];if(e&&Number.isFinite(e.x)&&Number.isFinite(e.y)&&e.x>=1&&e.x<=10&&e.y>=1&&e.y<=10)evaluations[key]={x:e.x,y:e.y,source:'manual',reason:typeof e.reason==='string'?e.reason.slice(0,800):''}}return {id:'n'+i,group:hmws[b.hmws.findIndex(h=>h.id===n.group)]?.id||null,face:n.face,text:n.text.slice(0,600),likes:Number.isFinite(n.likes)?Math.max(0,Math.min(n.likes,9999)):0,locked:!!n.locked,liked:!!n.liked,evaluations}}),attachments:(b.attachments||[]).filter(a=>typeof a.name==='string'&&typeof a.data==='string'&&/^data:(image\/(png|jpeg|webp|gif)|application\/pdf);base64,[A-Za-z0-9+/=]+$/.test(a.data)&&a.data.length<7*1024*1024).slice(0,8).map(a=>({name:a.name.slice(0,160),type:a.type,data:a.data,size:a.size}))}}
async function handleFiles(files){const valid=[...files].filter(f=>['image/png','image/jpeg','image/webp','image/gif','application/pdf'].includes(f.type));if(!valid.length)return toast('Choose a PNG, JPG, WebP, GIF or PDF.');snapshot();let added=0;for(const file of valid){if(file.size>5*1024*1024){toast(file.name+' is larger than 5 MB.');continue}if(state.attachments.length>=8){toast('Up to eight attachments per board.');break}const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});state.attachments.push({name:file.name,size:file.size,type:file.type,data});added++}save();state.stage=0;render();toast(storageOk?`${added} file${added===1?'':'s'} attached to your brief.`:'Files added but storage is full. Export this board before leaving.')}
function showHelp(){modal('Room to think',`<div class="shortcuts"><div><span>Add a thought</span><span>Pick a toolbar color</span></div><div><span>Edit a note</span><kbd>Double-click / Enter</kbd></div><div><span>Pan the canvas</span><kbd>Space + drag</kbd></div><div><span>Select / hand tool</span><kbd>V / H</kbd></div><div><span>Toggle Cube Companion</span><kbd>Q</kbd></div><div><span>Zoom</span><kbd>⌘ / Ctrl + scroll</kbd></div><div><span>Undo / redo</span><kbd>⌘Z / ⌘⇧Z</kbd></div><div><span>Remove a note</span><kbd>Delete</kbd></div></div><p style="margin:24px 0 0;font-size:13px">This workspace is for your own ideas. Boards are saved on this device. Export a copy for safekeeping or to share.</p><a class="demo-link" href="../prototype/" target="_blank" rel="noopener">Open the blank prototype</a>`,`<button class="btn primary" data-close>Got it</button>`)}
function spin(){if(!aiReady)return toast('Cube AI is not connected yet. You can add your own ideas.');}
function ask(){toast('Cube AI is not connected yet.');}
// Extend the existing event handlers with production board actions.
const bindBase=bind;
bind=function(){bindBase();const app=$('#app'),changeBase=app.onchange,clickBase=app.onclick;
 syncProjectTitleInputs();
 const titleInput=$('#header-project-title'),titleLabel=$('#project-title-label');
 if(titleInput&&titleLabel){
  let renaming=false;
  titleInput.hidden=true;titleLabel.hidden=false;
  const finishRename=(commit,returnFocus=false)=>{
   if(!renaming)return;
   renaming=false;
   if(commit)saveProjectTitle(titleInput.value);else syncProjectTitleInputs();
   titleInput.hidden=true;titleLabel.hidden=false;
   if(returnFocus)titleLabel.focus();
  };
  titleLabel.onclick=e=>{
   e.stopPropagation();if(renaming)return;
   renaming=true;titleInput.value=state.title==='Untitled board'?'':state.title;
   titleLabel.hidden=true;titleInput.hidden=false;titleInput.focus();titleInput.select();
  };
  // Native button activation should not also trigger canvas shortcuts.
  titleLabel.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')e.stopPropagation();};
  titleInput.onblur=()=>finishRename(true);
  titleInput.onkeydown=e=>{
   if(e.key!=='Enter'&&e.key!=='Escape')return;
   e.stopPropagation();
   if(e.isComposing||e.keyCode===229)return;
   e.preventDefault();finishRename(e.key==='Enter',true);
  };
 }
 app.onclick=e=>{const pick=e.target.closest('[data-select-note]');if(pick){selected=pick.dataset.selectNote;renderBoard();renderPanel();return}const live=e.target.closest('[data-live-action]');if(live){if(live.dataset.liveAction==='rate')return rateSelected();return toast('Cube AI is not connected yet.')}const file=e.target.closest('[data-open-file]');if(file){const a=state.attachments[Number(file.dataset.openFile)];if(a?.data){const [meta,data]=a.data.split(',');const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:a.type}));const link=document.createElement('a');link.href=url;link.download=a.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}return}clickBase(e)};
 app.onchange=e=>{if(e.target.dataset.rating){$('#rating-'+e.target.dataset.rating+'-value').textContent=e.target.value;return}if(e.target.id==='rating-reason'){const n=state.notes.find(n=>n.id===selected),s=n?.evaluations?.[state.axis];if(s){snapshot();s.reason=e.target.value.trim();save()}return}if(e.target.id==='board-title'){snapshot();saveContext();return}changeBase(e);if(e.target.id==='goal'||e.target.id==='audience')updateWorkflowControls()};
 app.oninput=e=>{if(e.target.id==='goal'||e.target.id==='audience'||e.target.dataset.hmw)updateWorkflowControls();if(e.target.dataset.rating)$('#rating-'+e.target.dataset.rating+'-value').textContent=e.target.value};
 if($('#context-form'))$('#context-form').onsubmit=e=>{e.preventDefault();if(changeStage(1))toast('Your brief is ready. Add a question to begin.')};
};
render();registerTools();
