"""Refresh the assistant's reference text from our own website, without modifying it."""
import json
from pathlib import Path
from html.parser import HTMLParser

class ExtractText(HTMLParser):
    def __init__(self, desktop):
        super().__init__()
        self.desktop, self.stack, self.start, self.text = desktop, [], None, []
    def handle_starttag(self, tag, attrs):
        if tag in ['img', 'input', 'br', 'hr', 'meta', 'link', 'source', 'wbr', 'area', 'embed']: return
        self.stack.append(tag)
        target = 'case-desktop' in dict(attrs).get('class', '').split() if self.desktop else tag == 'main'
        if target: self.start = len(self.stack)
    def handle_endtag(self, tag):
        if tag in self.stack:
            index = len(self.stack) - 1 - self.stack[::-1].index(tag)
            self.stack = self.stack[:index]
            if self.start and len(self.stack) < self.start: self.start = None
    def handle_data(self, data):
        if self.start and not any(tag in self.stack for tag in ['script', 'style', 'nav', 'aside', 'button']):
            if data.strip(): self.text.append(' '.join(data.split()))

ROOT = Path(__file__).resolve().parents[1]
sources = [('about', 'about.html'), *[(slug, f'{slug}/index.html') for slug in (
    'project-3-hhi', 'project-1-lighthouse', 'project-2-southerncrafted', 'project-4-nalu')],
    ('project-3-hhi-preview', 'hhi-preview/index.html'),
    ('project-1-lighthouse-preview', 'lighthouse-preview/index.html')]
knowledge = {}
for key, filename in sources:
    source = (ROOT / filename).read_text()
    parser = ExtractText('case-desktop' in source)
    parser.feed(source)
    text = '\n'.join(parser.text)
    knowledge[key] = {'source': '/' + filename.replace('index.html', ''), 'text': text[:24000]}
(ROOT / 'server/knowledge.js').write_text('// Generated by scripts/build-chat-knowledge.py. Public portfolio text only.\nexport default ' + json.dumps(knowledge, ensure_ascii=False, indent=2) + ';\n')
print(f'Updated {len(knowledge)} portfolio references.')
